name: fxblue
description: My Fedora Silverblue image based on uBlue

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: dnf
    repos:
      cleanup: true
      copr:
        - agriffis/neovim-nightly
        - monkeygold/nautilus-open-any-terminal
        - pgdev/ghostty

    install:
      packages:
        - fish
        - wl-clipboard
        - neovim
        - gcc
        - g++
        - podman-compose
        - podman-docker
        - nautilus-open-any-terminal
        - libcurl-devel
        - luajit-devel
        - lua
        - inotify-tools
        - android-tools
        - ghostty

    remove:
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - nvtop
        - yelp
        - gnome-tour
        - gnome-classic-session
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-background-logo
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list
        - gnome-tweaks
        - gnome-system-monitor
        - vim-enhanced
        - ptyxis

  - type: files
    files:
      - source: system
        destination: /

  - type: kargs
    kargs:
      - slab_nomerge
      - init_on_alloc=1
      - init_on_free=1
      - page_alloc.shuffle=1
      - pti=on
      - randomize_kstack_offset=on
      - vsyscall=none
      - module.sig_enforce=1
      - lockdown=confidentiality
      - quiet
      - loglevel=0
      - random.trust_cpu=off
      - random.trust_bootloader=off
      - intel_iommu=on
      - amd_iommu=force_isolation
      - iommu=force
      - iommu.passthrough=0
      - iommu.strict=1
      - mitigations=auto,nosmt
      - spectre_v2=on
      - spec_store_bypass_disable=on
      - l1d_flush=on
      - gather_data_sampling=force

  - type: script
    snippets:
      - echo "Hidden=true" | tee -a /usr/share/applications/{nvidia-settings,fish,nvim}.desktop
      - ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld

  - type: initramfs

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Alphabetical App Grid
      - 779 # Clipboard Indicator
      - Focused Window D-Bus
      - Run or raise
      - Rounded Window Corners Reborn
      - Tiling Assistant

  - type: default-flatpaks
    system:
      install:
        - app.zen_browser.zen
        - io.missioncenter.MissionCenter

  - type: gschema-overrides
    include:
      - zz1-fxblue.gschema.override

  - type: brew
    brew-analytics: false

  - type: chezmoi
    repository: https://github.com/flexagoon/dotfiles

  - type: signing
