name: fxblue
description: My Fedora Silverblue image based on uBlue

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/repo/fedora-%OS_VERSION%/agriffis-neovim-nightly-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo

    install:
      - fish
      - wl-clipboard
      - neovim
      - gcc
      - g++
      - podman-compose
      - tlp
      - tlp-rdw
      - nautilus-open-any-terminal
      - libcurl-devel
      - zenity
      - luajit-devel
      - inotify-tools

    remove:
      - firefox
      - firefox-langpacks
      - htop
      - nvtop
      - yelp
      - gnome-terminal
      - gnome-terminal-nautilus
      - gnome-tour
      - gnome-classic-session
      - gnome-classic-session-xsession
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-tweaks
      - vim-enhanced
      - power-profiles-daemon

  - type: files
    files:
      - usr: /usr

  - type: systemd
    system:
      enabled:
        - tlp.service

  - type: script
    scripts:
      - ld.sh
      - hide-app-icons.sh
      - authselect.sh

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Alphabetical App Grid
      - 779 # Clipboard Indicator
      - Focused Window D-Bus
      - Run or raise
      - Rounded Window Corners Reborn

  - type: default-flatpaks
    system:
      install:
        - org.mozilla.firefox
        - org.wezfurlong.wezterm

  - type: gschema-overrides
    include:
      - zz1-fxblue.gschema.override

  - type: brew
    brew-analytics: false

  - type: chezmoi
    repository: https://github.com/flexagoon/dotfiles

  - type: signing
