name: fxblue
description: My Fedora Silverblue image based on uBlue

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - fish
      - gnome-shell-extension-blur-my-shell
      - wl-clipboard

    remove:
      - firefox
      - firefox-langpacks
      - htop
      - nvtop
      - yelp
      - gnome-terminal
      - gnome-terminal-nautilus
      - gnome-tour
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-tweaks
      - gnome-extensions-app

  - type: files
    files:
      - usr: /usr

  - type: default-flatpaks
    system:
      install:
        - org.mozilla.firefox
        - org.wezfurlong.wezterm

  - type: script
    scripts:
      - signing.sh
      - nautilus-open-any-terminal.sh
      - hide-app-icons.sh

  - type: bling
    install:
      - dconf-update-service
