name: fxblue
description: My Fedora Silverblue image based on uBlue

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - fish
      - nautilus-python
    remove:
      - firefox
      - firefox-langpacks
      - gnome-terminal-nautilus
      - gnome-tour
      - yelp
      - gnome-terminal
      - htop
      - nvtop
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list

  - type: files
    files:
      - usr: /usr

  - type: default-flatpaks
    system:
      install:
        - org.mozilla.firefox
        - com.raggesilver.BlackBox

  - type: script
    scripts:
      - signing.sh
